Update workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,7 +34,6 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     needs: test
-    # if: github.ref == 'refs/heads/main'
 
     steps:
       - name: Checkout Code
@@ -62,6 +61,9 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd /swat/barblog
+            if [ ! -f .env ]; then
+              echo ".env not found" && exit 1
+            fi
             docker compose -f compose.yaml pull web
             docker compose -f compose.yaml up -d
             docker system prune --force
